base:
  project_name: salamandra-cot
  log_level: DEBUG
  models_dir: ../models
  datasets_dir: ../datasets
  checkpoints_dir: ./checkpoints
  generations_dir: ./generations
  evaluations_dir: ./evaluations
  hf_org_id: logits-blog

data:
  magpie_v2_deepseek_r1:
    dir_path: magpie_v2_deepseek_r1/data
    name: magpie_v2_deepseek_r1
    format: parquet
    hf_dataset_id: Magpie-Align/Magpie-Reasoning-V2-250K-CoT-Deepseek-R1-Llama-70B
    src_lang: English
    tgt_lang: Spanish
    # max_length: 2048 # filtering
    # max_samples: 10000 # sampling
    col_names: # map column names to dataset schema
      instruction: instruction
      output: response

format_datasets:
  raw_dir_path: raw
  format_dir_path: formatted

preprocess_datasets:
  preprocess_dir_path: preprocessed

dataset_translate:
  translate_dir_path: translated
  checkpoint_step: 100
  model:
    dir_path: salamandrata_2b
    hf_model_id: BSC-LT/salamandraTA-2B
    prompt_template: "[{src_lang}] {stmt} \n[{tgt_lang}]"
    model_args:
      use_cache: true
      do_sample: false
      num_beams: 5
      max_new_tokens: 128
      early_stopping: true

convert_datasets:
  convert_dir_path: converted
  template: chatml
  
evaluate_models:
  models:
    # salamandra_2b_cot_eng:
    #   dir_path: axolotl/salamandra_2b_cot_eng
    salamandra_2b:
      dir_path: salamandra_2b
  few_shot: 3
  truncate_few_shots: 1 # {0: no truncation, 1: truncate}
  tasks:
    - "harness|bbh:causal_judgment"
    - "harness|bbh:date_understanding"
    - "harness|bbh:disambiguation_qa"
    - "harness|bbh:geometric_shapes"
    - "helm|mmlu"
    - "lighteval|gsm8k"