[tool.black]
line-length = 80
target_version = ['py311']
include = 'src\.pyi?$'
exclude = 'venv/'

[tool.isort]
profile = 'black'
py_version = 311
src_paths = ['src']
skip_glob = ["**/.env*", "**/.venv/*"]
