base_model: BSC-LT/salamandra-2b-instruct
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_8bit: true
load_in_4bit: false

bf16: true
fp16: false
tf32: false

strict: false
train_on_inputs: false

adapter: lora
lora_r: 16
lora_alpha: 32
lora_dropout: 0.05
lora_target_modules:
  - q_proj
  - v_proj
  - k_proj
  - o_proj
  - gate_proj
  - down_proj
  - up_proj

datasets:
  - path: json
    data_files: /mnt/SAMSUNG/development/datasets/converted/magpie_v2_deepseek_r1/magpie_v2_deepseek_r1.jsonl
    type: chat_template
    field_messages: messages
    message_field_role: role
    message_field_content: content

dataset_prepared_path: ../../datasets/axolotl/magpie_v2_deepseek_r1
output_dir: ../../models/axolotl/salamandra_2b_cot_eng

chat_template: chatml
default_system_message: |-
  You are a reasoning assistant. For every request:  
  1. Analyze the problem systematically  
  2. Break it down into logical steps  
  3. Explain your thinking process clearly  
  4. Conclude with a final answer

seed: 42 # Of Life, the Universe and Everything

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: true
group_by_length: false
  
hub_model_id: logits-blog/salamandra-2b-cot

dataset_processes: 20

gradient_accumulation_steps: 8
micro_batch_size: 1
num_epochs: 2
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-5
max_steps: 10000

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
evals_per_epoch: 0
eval_table_size:
save_strategy: steps
save_steps: 500
save_total_limit: 5
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <unk>
  bos_token: <s>
  eos_token: </s>
  unk_token: <unk>